name: enigma-sento-backend

services:
  tei-dev:
    image: ghcr.io/huggingface/text-embeddings-inference:1.6
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - tei-dev-data:/data
    ports:
      - 8080:80
    command: ['--model-id=sentence-transformers/all-MiniLM-L6-v2']

  vector-db-dev:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.toml
    volumes:
      - vector-db-dev-data:/qdrant/storage

  db-dev:
    image: postgres:latest
    env_file:
      - .env.docker
    ports:
      - '5433:5432'
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  minio-dev:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env.docker
    volumes:
      - minio-dev-data:/data
    command: server --console-address ":9001" /data

  mongo-dev:
    image: mongo
    env_file:
      - .env.docker
    ports:
      - 27017:27017
    volumes:
      - mongo-dev-data:/data/db

  redis-dev:
    image: bitnami/redis
    env_file:
      - .env.docker
    ports:
      - '6378:6379'
    volumes:
      - 'redis-dev-data:/bitnami/redis/data'

volumes:
  db-dev-data:
  minio-dev-data:
  keycloak-dev-data:
  mongo-dev-data:
  redis-dev-data:
  tei-dev-data:
  vector-db-dev-data:

configs:
  qdrant_config:
    content: |
      log_level: INFO
