/* eslint-disable */
export default async () => {
    const t = {
        ["./user/entities/user.entity"]: await import("./user/entities/user.entity"),
        ["./auth/dto/signIn-auth.dto"]: await import("./auth/dto/signIn-auth.dto"),
        ["./user/dto/create-user.dto"]: await import("./user/dto/create-user.dto"),
        ["./user/dto/findAll-user.dto"]: await import("./user/dto/findAll-user.dto")
    };
    return { "@nestjs/swagger": { "models": [[import("./user/dto/create-user.dto"), { "CreateUserRequestDto": { displayName: { required: true, type: () => String }, username: { required: true, type: () => String }, password: { required: true, type: () => String }, role: { required: true, type: () => Object } }, "CreateUserResponseDto": { message: { required: true, type: () => String }, data: { required: true, type: () => ({ id: { required: true, type: () => String }, username: { required: true, type: () => String }, displayName: { required: true, type: () => String }, role: { required: true, type: () => Object }, createdAt: { required: true, type: () => Date }, updatedAt: { required: true, type: () => Date } }) } } }], [import("./auth/dto/signIn-auth.dto"), { "SignInAuthRequestDto": { username: { required: true, type: () => String }, password: { required: true, type: () => String } }, "SignInAuthResponseDto": { message: { required: true, type: () => String }, data: { required: true, type: () => ({ token: { required: true, type: () => String }, user: { required: true, type: () => ({ id: { required: true, type: () => String }, displayName: { required: true, type: () => String }, role: { required: true, type: () => Object } }) } }) } } }], [import("./user/entities/user.entity"), { "User": { id: { required: true, type: () => String }, displayName: { required: true, type: () => String }, username: { required: true, type: () => String }, role: { required: true, type: () => Object }, createdAt: { required: true, type: () => Date }, updatedAt: { required: true, type: () => Date } } }], [import("./user/dto/findAll-user.dto"), { "FindAllUserResponseDto": { message: { required: true, type: () => String }, data: { required: true, type: () => [t["./user/entities/user.entity"].User] } } }]], "controllers": [[import("./app.controller"), { "AppController": { "getHello": { summary: "Welcome message" } } }], [import("./auth/auth.controller"), { "AuthController": { "signIn": { summary: "Sign in", type: t["./auth/dto/signIn-auth.dto"].SignInAuthResponseDto } } }], [import("./user/user.controller"), { "UserController": { "create": { summary: "Create new user", type: t["./user/dto/create-user.dto"].CreateUserResponseDto }, "findAll": { summary: "Get all users", type: t["./user/dto/findAll-user.dto"].FindAllUserResponseDto } } }]] } };
};